### ISSUE TITLE
Assign LIT tech to create the rest of workstations via loggins admin page, from spreadsheet

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/loggins#102]
2nd floor is done, but we could use some help entering workstations on the other floors.

The designated individual can contact me for admin login URL and credentials, and directions.

No milestone currently assigned, but target completion by Aug. 30.  There are about 60 more needing to be entered.  It should take approx. 2 hours.

**Comment by kerchner** [comment]
Remaining:  Lab computers on Entrance floor, and 7th floor computers.  Moving this out of m5 so that we can tag and deploy m5.

**Comment by kerchner** [comment]
Matt, any updates on adding the MAC addresses for the lab computers to the spreadsheet?

**Comment by kilahimm** [comment]
I believe i added the last VDI mac address yesterday.  Macs will not need MAC addresses.
