### ISSUE TITLE
Allow null=True for location.ipaddress and display ip_address column in admin view

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/loggins#145]
This is a prerequisite to #152

**Comment by kerchner** [comment]
Note that using GenericIPAddressField instead of IPAddressField (which, anyway, is deprecated) seems to successfully work around this issue:  https://code.djangoproject.com/ticket/5622

**Comment by kilahimm** [comment]
Bogus IP addresses replaced with actual IPs and test machines removed from DB
