### ISSUE TITLE
Add mimeparse to requirements.txt

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/loggins#170]
Deployment breaks unless the system has it.  Need to install to the environment, so add it to requirements.txt .  This is a dependency of tastypie.

**Comment by dchud** [comment]
If it's a tastypie requirement, shouldn't installing tastypie pull it in?

**Comment by kerchner** [comment]
This issue has recently been fixed in django-tastypie - see https://github.com/toastdriven/django-tastypie/issues/1004

It should be resolvable by doing a pip re-install (i.e.  `pip uninstall -r requirements.txt`, then `pip install -r requirements.txt`  Verify that mimeparse was correctly identified as a dependency of django-tastypie and installed by running `pip freeze`
