### ISSUE TITLE
"Last Updated" alignment on mobile

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/loggins#171]
Text appears misaligned on mobile displays.

**Comment by kerchner** [comment]
Matt, how is it appearing on your mobile display?

Maybe we can consider removing the 'last updated' message; since we update 2x a minute (and will be moving to even live-r updates with AJAX), I'm not sure how much value this adds.

**Comment by dchud** [comment]
I like seeing it down there, it reinforces my perception of its "freshness".

**Comment by kerchner** [comment]
Move to left
