### ISSUE TITLE
Bootswatch cutoff when using sign display at 250

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/loggins#176]
computers.library.gwu.edu/gelman/sign/250 cuts off bootswatch

**Comment by kerchner** [comment]
Matt, do we even need bootswatches to display for the /sign view?  Do you and Robin feel it would it look cleaner without?

**Comment by dchud** [comment]
Just to be clear about terminology, do you mean the banner at the top of the page?  "bootswatch" is really the name of the strategy of applying our own stylesheet over bootstrap, which in this case includes the banners at top and bottom...

**Comment by kerchner** [comment]
Sorry, yes, I meant the banners at top and bottom.  I thought about it some more and I think I'll keep the banners but tailor the info to only what's needed on the sign.  On the top I'll eliminate the "GW Libraries" link and slide "computers.library.gwu.edu" over to the left (to publicize the URL).  On the bottom I'll eliminate the address text but keep the blue swatch.

**Comment by dchud** [comment]
okay, and don't hesitate to bring @StudioZut in on this...
