### ISSUE TITLE
Django management command to capture SNMP state

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/loggins#29]
Dan C. recommends 'createsessions' as an example django management command

The intention is to run this command as a cron job.

**Comment by kilahimm** [comment]
#!/bin/sh
#Usage: "./snmpwalk.sh 128.164.212"
for i in {0..255};
do {
        OUTPUT=$(snmpwalk -c public -v 2c $1.$i iso.3.6.1.4.1.25071.1.2.6.1.1.2.1)
        if [[ "$OUTPUT" == _"pcoip"_ ]];
        then
                hostname=$(echo $OUTPUT | grep -o 'pcoip.*[^"]');
                echo "$hostname - $1.$i"
                echo "$hostname - $1.$i" >> snmpmachines.txt;
        fi
}
done

**Comment by kilahimm** [comment]
#!/bin/sh
#Usuage: ./snmpstatus.sh snmpmachines.txt
FILENAME=$1
count=0
cat $FILENAME | while read LINE
do {
        let count++
        HOSTADDRESS=$(echo $LINE | grep -o '128._[^"]');
        OUTPUT1=$(snmpwalk -c public -v 2c $HOSTADDRESS iso.3.6.1.4.1.25071.1.2.6.1.1.2.1);
        OUTPUT2=$(snmpwalk -c public -v 2c $HOSTADDRESS 1.3.6.1.4.1.25071.1.1.2.1.1.3.1 | grep -Eo '.$');
        if [[ "$OUTPUT1" == *"pcoip"_ ]];
        then
                hostname=$(echo $OUTPUT1 | grep -o 'pcoip.*[^"]')
                status=$OUTPUT2
                echo "$HOSTADDRESS - $hostname - $status"
                echo "$HOSTADDRESS - $hostname - $status" >> snmpstatus.txt
        else
                echo "$HOSTADDRESS - - 2"
                echo "$HOSTADDRESS - - 2" >> snmpstatus.txt
        fi
}
done
