### ISSUE TITLE
Add signals for state changes

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/loggins#34]
State changes and associated (pre-save) actions:

(0 = available; 1 = logged in; 2 = unreachable)

0 -> 0   do nothing
0 -> 1   update last_login_time
0 -> 2   update last_unreachable_time
1 -> 0   create session (type = login); clear last_login_time
1 -> 1   do nothing
1 -> 2   update last_unreachable_time; create session (type = login); clear last_login_time
2 -> 0   create session (type = unreachable); clear last_unreachable_time
2 -> 1   update last_login_time; create session (type = unreachable); clear last_unreachable_time
2 -> 2   do nothing

**Comment by dchud** [comment]
presumably these would update `obs_state` and `obs_time` as appropriate, too?

**Comment by darshanrp** [comment]
`obs_state` and `obs_time` will be updated by default every time irrespective of the state change
