### ISSUE TITLE
Chmod 0700 on directory where mac script is deployed

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/loggins#43]

**Comment by kilahimm** [comment]
suggest skipping encryption of the script and storing on the macs with permissions 0700.

**Comment by kerchner** [comment]
Changing name of ticket in line with Matt's comment.

**Comment by kilahimm** [comment]
I'm going to bundle the Mac script before deployment into an app to encrypt it as well.  It's not perfect, but that plus chmod 0700 will make it well secured.

**Comment by kilahimm** [comment]
Mac scripts have been added to the deployment notes folder for the project.  I deployed an encrypted app and had ot use 0755 permissions for it to run as expected during login/logout.  Scripts and apps have been handed off to AT for deployed.

**Comment by kilahimm** [comment]
Mac scripts have been deployed successfully.
