### ISSUE TITLE
Cosmetic tweaks to improve appearance on mobile devices

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/loggins#66]

**Comment by kerchner** [comment]
Probably not needed but including here just in case

**Comment by kerchner** [comment]
Remove redundant wording (available, etc.)
Chris, please take a look and provide feedback.
Dan suggests adding media object tag.  Chris, what is the flag?

Please reassign to Dan K. after review.

**Comment by StudioZut** [comment]
The object tag: http://www.w3schools.com/tags/tag_object.asp

To make pages scale better within lower res windows and handheld, add this to the `<head>`:
`<meta name='viewport' content='width=device-width, initial-scale=1.0' />`
