### ISSUE TITLE
Decide on a name for the app

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/loggins#86]
Matt will need this to name the server.   Perhaps get ideas by looking at what other institutions (duke, etc.) have opted to call theirs.

**Comment by darshanrp** [comment]
Suggestion: LIBCAS - Library Computers Availability System

**Comment by dchud** [comment]
Alas, I am allergic to acronyms that don't have a direct-sounding meaning.  I'm leaning toward "computers" or "machines".

**Comment by kerchner** [comment]
"computers" probably best summarizes the intent.

**Comment by dchud** [comment]
computers.library.gwu.edu it is... boring, but clear!

**Comment by kerchner** [comment]
Done - it's "computers"
