### ISSUE TITLE
Create Lab floor for lab computers

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/loggins#90]

**Comment by kilahimm** [comment]
I'm going to have the lab computers labeled as: E-L-001, E-L-002, ect.

**Comment by kerchner** [comment]
Actually, can you label them as E-L01, E-L02, etc.?

**Comment by kilahimm** [comment]
Sure thing.

**Comment by kerchner** [comment]
Requires #159

**Comment by kerchner** [comment]
Fixed by #183  - implemented as a Zone on the Entrance Floor
